#!/usr/bin/env bash

python3 -m pip install --upgrade pip
python3 -m venv .env
source .env\bin\activate
pip install -U pip setuptools
pip install pandas
pip install serial
pip freeze > requirements.txt
